// ── Cake Product Data ──────────────────────────────────────────────────────
export const CAKES = [
  {
    id: 'cake-001',
    name: 'Midnight Chocolate Truffle',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop',
    price: 45,
    rating: 4.9,
    reviewCount: 128,
    category: 'Birthday Cakes',
    tags: ['Dark Cocoa', 'Ganache', 'Espresso'],
    description: 'Intense dark chocolate layers with espresso ganache and edible gold flakes. A true showstopper.',
    badge: 'Bestseller',
    badgeColor: 'bg-chocolate-900',
    dietary: ['standard'],
    flavors: ['dark-chocolate'],
    basePrice: 45,
  },
  {
    id: 'cake-002',
    name: 'Classic Vanilla Bean Rose',
    image: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&auto=format&fit=crop',
    price: 250,
    rating: 4.8,
    reviewCount: 45,
    category: 'Tiered Wedding',
    tags: ['Madagascar Vanilla', 'Swiss Meringue', 'Edible Florals'],
    description: 'Madagascar vanilla sponge with Swiss meringue buttercream and fresh rose petal adornments.',
    badge: null,
    dietary: ['standard'],
    flavors: ['vanilla-bean', 'swiss-meringue'],
    basePrice: 250,
  },
  {
    id: 'cake-003',
    name: 'Summer Berry Chantilly',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop',
    price: 55,
    rating: 4.7,
    reviewCount: 89,
    category: 'Birthday Cakes',
    tags: ['Light Sponge', 'Mascarpone', 'Fresh Berries'],
    description: 'Light vanilla sponge with chantilly cream and a medley of fresh seasonal berries.',
    badge: 'Gluten-Free Option',
    badgeColor: 'bg-green-700',
    dietary: ['standard', 'eggless'],
    flavors: ['vanilla-bean', 'lemon-raspberry'],
    basePrice: 55,
  },
  {
    id: 'cake-004',
    name: 'Red Velvet Dream',
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&auto=format&fit=crop',
    price: 45,
    rating: 4.8,
    reviewCount: 203,
    category: 'Birthday Cakes',
    tags: ['Red Velvet', 'Cream Cheese', 'Vanilla'],
    description: 'Signature artisan red velvet sponge delicately layered with Madagascar vanilla bean cream cheese frosting.',
    badge: 'Bestseller',
    badgeColor: 'bg-chocolate-900',
    dietary: ['standard', 'eggless'],
    flavors: ['red-velvet'],
    basePrice: 45,
  },
  {
    id: 'cake-005',
    name: 'Lemon Citrus Delight',
    image: 'https://images.unsplash.com/photo-1602351447937-745cb720612f?w=600&auto=format&fit=crop',
    price: 48,
    rating: 4.6,
    reviewCount: 67,
    category: 'Anniversary',
    tags: ['Lemon Curd', 'Raspberry', 'Chiffon'],
    description: 'Zesty lemon chiffon with homemade raspberry compote and a delicate lemon curd filling.',
    badge: null,
    dietary: ['standard', 'vegan'],
    flavors: ['lemon-raspberry'],
    basePrice: 48,
  },
  {
    id: 'cake-006',
    name: 'Caramel Praline Gateau',
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&auto=format&fit=crop',
    price: 52,
    rating: 4.9,
    reviewCount: 91,
    category: 'Anniversary',
    tags: ['Salted Caramel', 'Praline', 'Almond'],
    description: 'Buttery almond sponge with layers of salted caramel mousse and crunchy praline.',
    badge: null,
    dietary: ['standard'],
    flavors: ['salted-caramel'],
    basePrice: 52,
  },
  {
    id: 'cake-007',
    name: 'Strawberry Cream Puff Tower',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop',
    price: 180,
    rating: 4.7,
    reviewCount: 34,
    category: 'Tiered Wedding',
    tags: ['Choux Pastry', 'Diplomat Cream', 'Strawberry'],
    description: 'A stunning tower of golden profiteroles filled with strawberry diplomat cream.',
    badge: null,
    dietary: ['standard'],
    flavors: ['vanilla-bean'],
    basePrice: 180,
  },
  {
    id: 'cake-008',
    name: 'Matcha Green Tea Marble',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?w=600&auto=format&fit=crop',
    price: 50,
    rating: 4.5,
    reviewCount: 56,
    category: 'Cupcakes',
    tags: ['Matcha', 'White Chocolate', 'Japanese'],
    description: 'Ceremonial grade matcha sponge swirled with white chocolate ganache and azuki bean paste.',
    badge: 'Sugar-Free Option',
    badgeColor: 'bg-blue-700',
    dietary: ['sugar-free', 'vegan'],
    flavors: ['pistachio-rose'],
    basePrice: 50,
  },
  {
    id: 'cake-009',
    name: 'Pistachio Rose Delight',
    image: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=600&auto=format&fit=crop',
    price: 58,
    rating: 4.8,
    reviewCount: 42,
    category: 'Anniversary',
    tags: ['Pistachio', 'Rose Water', 'Cardamom'],
    description: 'Fragrant pistachio frangipane with rose water cream and edible dried rose petals.',
    badge: null,
    dietary: ['standard', 'eggless'],
    flavors: ['pistachio-rose'],
    basePrice: 58,
  },
  {
    id: 'cake-010',
    name: 'Assorted Mini Cupcakes',
    image: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600&auto=format&fit=crop',
    price: 35,
    rating: 4.6,
    reviewCount: 185,
    category: 'Cupcakes',
    tags: ['Variety', 'Buttercream', 'Mini'],
    description: 'A dozen beautifully decorated mini cupcakes in a variety of seasonal flavors and toppings.',
    badge: null,
    dietary: ['standard', 'eggless'],
    flavors: ['vanilla-bean', 'dark-chocolate', 'lemon-raspberry'],
    basePrice: 35,
  },
  {
    id: 'cake-011',
    name: 'Fondant Unicorn Cake',
    image: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?w=600&auto=format&fit=crop',
    price: 95,
    rating: 4.9,
    reviewCount: 77,
    category: 'Birthday Cakes',
    tags: ['Fondant', 'Unicorn', 'Rainbow Layers'],
    description: 'Magical rainbow layered cake with hand-sculpted fondant unicorn topper and edible glitter.',
    badge: null,
    dietary: ['standard', 'eggless'],
    flavors: ['vanilla-bean', 'lemon-raspberry'],
    basePrice: 95,
  },
  {
    id: 'cake-012',
    name: 'Opera Coffee Gateau',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop',
    price: 62,
    rating: 4.7,
    reviewCount: 53,
    category: 'Desserts',
    tags: ['Coffee', 'Almond Joconde', 'Ganache'],
    description: 'Classic French opera cake: almond joconde, coffee buttercream, and bittersweet ganache layers.',
    badge: null,
    dietary: ['standard'],
    flavors: ['dark-chocolate'],
    basePrice: 62,
  },
];

// ── Gallery Items ──────────────────────────────────────────────────────────
export const GALLERY_ITEMS = [
  {
    id: 'g-001',
    title: 'Floral Wedding Cascade',
    image: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=600&auto=format&fit=crop',
    category: 'Tiered Wedding Setups',
  },
  {
    id: 'g-002',
    title: 'Celestial Moon & Stars',
    image: 'https://images.unsplash.com/photo-1562777717-dc6984f65a63?w=600&auto=format&fit=crop',
    category: '3D Theme Cakes',
  },
  {
    id: 'g-003',
    title: 'Wonderland Book Stack',
    image: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?w=600&auto=format&fit=crop',
    category: '3D Theme Cakes',
  },
  {
    id: 'g-004',
    title: 'Leather Satchel Illusion',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&auto=format&fit=crop',
    category: '3D Theme Cakes',
  },
  {
    id: 'g-005',
    title: 'Dark Floral Bouquet',
    image: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop',
    category: 'Tiered Wedding Setups',
  },
  {
    id: 'g-006',
    title: 'Vintage Heart Lace',
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=600&auto=format&fit=crop',
    category: 'Vintage Heart Cakes',
  },
  {
    id: 'g-007',
    title: 'Cherry on Top Classic',
    image: 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600&auto=format&fit=crop',
    category: 'Baby Showers',
  },
  {
    id: 'g-008',
    title: 'Elegant White Tiered',
    image: 'https://images.unsplash.com/photo-1549040132-3922d9d16562?w=600&auto=format&fit=crop',
    category: 'Tiered Wedding Setups',
  },
  {
    id: 'g-009',
    title: 'Berry Chantilly Tower',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600&auto=format&fit=crop',
    category: 'Baby Showers',
  },
  {
    id: 'g-010',
    title: 'Pastel Macaroon Stack',
    image: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600&auto=format&fit=crop',
    category: 'Baby Showers',
  },
  {
    id: 'g-011',
    title: 'Gold Leaf Marble Drip',
    image: 'https://images.unsplash.com/photo-1614707267537-b85aaf00c4b7?w=600&auto=format&fit=crop',
    category: 'Vintage Heart Cakes',
  },
  {
    id: 'g-012',
    title: 'Midnight Chocolate Dream',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop',
    category: '3D Theme Cakes',
  },
];

// ── Categories ──────────────────────────────────────────────────────────────
export const CATEGORIES = ['All', 'Birthday Cakes', 'Tiered Wedding', 'Anniversary', 'Cupcakes', 'Desserts'];

// ── Gallery Filter Categories ────────────────────────────────────────────────
export const GALLERY_CATEGORIES = ['All', '3D Theme Cakes', 'Tiered Wedding Setups', 'Baby Showers', 'Vintage Heart Cakes'];

// ── Reviews ─────────────────────────────────────────────────────────────────
export const REVIEWS = [
  {
    id: 'r-001',
    name: 'Sarah Mitchell',
    rating: 5,
    text: 'The wedding cake was absolutely stunning and tasted even better than it looked. Our guests couldn\'t stop complimenting it. Will definitely order again for every special occasion!',
    date: 'November 2024',
    product: 'Classic Vanilla Bean Rose',
  },
  {
    id: 'r-002',
    name: 'James & Priya',
    rating: 5,
    text: 'We ordered a custom 3-tier cake for our anniversary and it was beyond our expectations. The attention to detail and the flavors were impeccable. True artisans!',
    date: 'October 2024',
    product: 'Custom Tiered Wedding Cake',
  },
  {
    id: 'r-003',
    name: 'Amara Chen',
    rating: 5,
    text: 'I\'ve ordered from many bakeries, but Cake of Paradise is on another level. The Midnight Chocolate Truffle was rich, moist, and absolutely divine. My birthday was made!',
    date: 'December 2024',
    product: 'Midnight Chocolate Truffle',
  },
];

// ── Baker Values ─────────────────────────────────────────────────────────────
export const BAKER_VALUES = [
  {
    icon: '🌿',
    title: '100% Fresh Ingredients',
    description: 'We never compromise on quality, sourcing the finest ingredients for every bake.',
  },
  {
    icon: '🎨',
    title: 'Custom Artisanal Designs',
    description: 'Unique creations tailored to your vision, crafted with artistic precision.',
  },
  {
    icon: '🚚',
    title: 'On-Time Doorstep Delivery',
    description: 'Carefully transported to ensure your masterpiece arrives in perfect condition.',
  },
];
